const ListData = [
  [
    {
      name: 'Phân tích & thiết kế hệ thống',
      id: 'TH02037',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 8.5,
      grade10: 8.7,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Cấu trúc dữ liệu và giải thuật',
      id: 'TH02016',
      count: 3,
      gradeCC: 9,
      gradeGK: 6,
      gradeCK: 8,
      grade10: 7.2,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Những NLCB của CN Mác-Lênin 2',
      id: 'ML01002',
      count: 3,
      gradeCC: 9,
      gradeGK: 7,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'TH cấu trúc DL&giải thuật',
      id: 'TH02035',
      count: 3,
      gradeCC: 9,
      gradeGK: 9,
      gradeCK: 8,
      grade10: 8.5,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Phát triển ứng dụng Web',
      id: 'TH03012',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Kỹ năng làm việc nhóm',
      id: 'KN01005',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Giáo dục quốc phòng 3',
      id: 'QS01003',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Tư tưởng Hồ Chí Minh',
      id: 'CML01005	',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
  ],
  [
    {
      name: 'Phân tích & thiết kế hệ thống',
      id: 'TH02037',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 8.5,
      grade10: 8.7,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Cấu trúc dữ liệu và giải thuật',
      id: 'TH02016',
      count: 3,
      gradeCC: 9,
      gradeGK: 6,
      gradeCK: 8,
      grade10: 7.2,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Những NLCB của CN Mác-Lênin 2',
      id: 'ML01002',
      count: 3,
      gradeCC: 9,
      gradeGK: 7,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'TH cấu trúc DL&giải thuật',
      id: 'TH02035',
      count: 3,
      gradeCC: 9,
      gradeGK: 9,
      gradeCK: 8,
      grade10: 8.5,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Phát triển ứng dụng Web',
      id: 'TH03012',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Kỹ năng làm việc nhóm',
      id: 'KN01005',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Giáo dục quốc phòng 3',
      id: 'QS01003',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Tư tưởng Hồ Chí Minh',
      id: 'CML01005	',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
  ],
  [
    {
      name: 'Phân tích & thiết kế hệ thống',
      id: 'TH02037',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 8.5,
      grade10: 8.7,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Cấu trúc dữ liệu và giải thuật',
      id: 'TH02016',
      count: 3,
      gradeCC: 9,
      gradeGK: 6,
      gradeCK: 8,
      grade10: 7.2,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Những NLCB của CN Mác-Lênin 2',
      id: 'ML01002',
      count: 3,
      gradeCC: 9,
      gradeGK: 7,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'TH cấu trúc DL&giải thuật',
      id: 'TH02035',
      count: 3,
      gradeCC: 9,
      gradeGK: 9,
      gradeCK: 8,
      grade10: 8.5,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Phát triển ứng dụng Web',
      id: 'TH03012',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Kỹ năng làm việc nhóm',
      id: 'KN01005',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Giáo dục quốc phòng 3',
      id: 'QS01003',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Tư tưởng Hồ Chí Minh',
      id: 'CML01005	',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
  ],
  [
    {
      name: 'Phân tích & thiết kế hệ thống',
      id: 'TH02037',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 8.5,
      grade10: 8.7,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Cấu trúc dữ liệu và giải thuật',
      id: 'TH02016',
      count: 3,
      gradeCC: 9,
      gradeGK: 6,
      gradeCK: 8,
      grade10: 7.2,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Những NLCB của CN Mác-Lênin 2',
      id: 'ML01002',
      count: 3,
      gradeCC: 9,
      gradeGK: 7,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'TH cấu trúc DL&giải thuật',
      id: 'TH02035',
      count: 3,
      gradeCC: 9,
      gradeGK: 9,
      gradeCK: 8,
      grade10: 8.5,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Phát triển ứng dụng Web',
      id: 'TH03012',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Kỹ năng làm việc nhóm',
      id: 'KN01005',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Giáo dục quốc phòng 3',
      id: 'QS01003',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Tư tưởng Hồ Chí Minh',
      id: 'CML01005	',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
  ],
  [
    {
      name: 'Phân tích & thiết kế hệ thống',
      id: 'TH02037',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 8.5,
      grade10: 8.7,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Cấu trúc dữ liệu và giải thuật',
      id: 'TH02016',
      count: 3,
      gradeCC: 9,
      gradeGK: 6,
      gradeCK: 8,
      grade10: 7.2,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Những NLCB của CN Mác-Lênin 2',
      id: 'ML01002',
      count: 3,
      gradeCC: 9,
      gradeGK: 7,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'TH cấu trúc DL&giải thuật',
      id: 'TH02035',
      count: 3,
      gradeCC: 9,
      gradeGK: 9,
      gradeCK: 8,
      grade10: 8.5,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Phát triển ứng dụng Web',
      id: 'TH03012',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Kỹ năng làm việc nhóm',
      id: 'KN01005',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Giáo dục quốc phòng 3',
      id: 'QS01003',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Tư tưởng Hồ Chí Minh',
      id: 'CML01005	',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
  ],
  [
    {
      name: 'Phân tích & thiết kế hệ thống',
      id: 'TH02037',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 8.5,
      grade10: 8.7,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Cấu trúc dữ liệu và giải thuật',
      id: 'TH02016',
      count: 3,
      gradeCC: 9,
      gradeGK: 6,
      gradeCK: 8,
      grade10: 7.2,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Những NLCB của CN Mác-Lênin 2',
      id: 'ML01002',
      count: 3,
      gradeCC: 9,
      gradeGK: 7,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'TH cấu trúc DL&giải thuật',
      id: 'TH02035',
      count: 3,
      gradeCC: 9,
      gradeGK: 9,
      gradeCK: 8,
      grade10: 8.5,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Phát triển ứng dụng Web',
      id: 'TH03012',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Kỹ năng làm việc nhóm',
      id: 'KN01005',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Giáo dục quốc phòng 3',
      id: 'QS01003',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Tư tưởng Hồ Chí Minh',
      id: 'CML01005	',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
  ],
  [
    {
      name: 'Quản lý dự án phần mềm',
      id: 'TH02037',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Học máy',
      id: 'TH02016',
      count: 3,
      gradeCC: 9,
      gradeGK: 6,
      gradeCK: 7,
      grade10: 7.0,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Xây dựng và phát triển phần mềm',
      id: 'ML01002',
      count: 3,
      gradeCC: 9,
      gradeGK: 7,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Kinh tế thương mại dịch vụ',
      id: 'TH02035',
      count: 3,
      gradeCC: 9,
      gradeGK: 9,
      gradeCK: 8,
      grade10: 8.5,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Quản lý môi trường',
      id: 'TH03012',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Kỹ năng làm việc nhóm',
      id: 'KN01005',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Giáo dục quốc phòng 3',
      id: 'QS01003',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Tư tưởng Hồ Chí Minh',
      id: 'CML01005	',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
  ],
  [
    {
      name: 'Phân tích & thiết kế hệ thống',
      id: 'TH02037',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 8.5,
      grade10: 8.7,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Cấu trúc dữ liệu và giải thuật',
      id: 'TH02016',
      count: 3,
      gradeCC: 9,
      gradeGK: 6,
      gradeCK: 8,
      grade10: 7.2,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Những NLCB của CN Mác-Lênin 2',
      id: 'ML01002',
      count: 3,
      gradeCC: 9,
      gradeGK: 7,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'TH cấu trúc DL&giải thuật',
      id: 'TH02035',
      count: 3,
      gradeCC: 9,
      gradeGK: 9,
      gradeCK: 8,
      grade10: 8.5,
      grade4: 3,
      gradeString: 'A',
    },
    {
      name: 'Phát triển ứng dụng Web',
      id: 'TH03012',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Kỹ năng làm việc nhóm',
      id: 'KN01005',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Giáo dục quốc phòng 3',
      id: 'QS01003',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
    {
      name: 'Tư tưởng Hồ Chí Minh',
      id: 'CML01005	',
      count: 3,
      gradeCC: 9,
      gradeGK: 8,
      gradeCK: 7.5,
      grade10: 7.5,
      grade4: 3,
      gradeString: 'B',
    },
  ],

  [],
];

export default ListData;
